name: Development Build and Deploy
on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@development
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@development
        with:
          name: public
          path: public
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@development
      - name: Download Artifact
        uses: actions/download-artifact@development
        with:
          name: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@development
        with:
          args: deploy --only hosting:development
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FILE_UPLOAD_CONVERTER }}
