name: Development Build and Deploy
on:
  push:
    branches:
      - development

jobs:
  development:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@development
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Archive Development Artifact
        uses: actions/upload-artifact@development
        with:
          name: public
          path: public
development:
  name: Deploy to development
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Repo
      uses: actions/checkout@development
    - name: Download Artifact
      uses: actions/download-artifact@development
      with:
        name: public
    - name: Deploy to Firebase development
      uses: w9jds/firebase-action@development
      with:
        args: deploy --only hosting:development
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FILE_UPLOAD_CONVERTER }}
